feat: pair-only chainlink oracle
alcueca/oracles pull request #9
Opened 2024-04-21 07:02 UTC by totomanov

2024-04-22 11:34 UTC, alcueca requested changes
I wonder if it is too confusing and unexpected that prices are always FP18 regardless of the quote asset. Everyone seems to get it wrong.

2024-04-22 11:34 UTC, alcueca commented on src/chainlink/ChainlinkOracle.sol
> +
This returns prices as the value of one asset unit in terms of the other, while the spec states the prices should always be FP18.

2024-04-22 11:34 UTC, alcueca commented on src/chainlink/ChainlinkOracle.sol
> +            return answer * DENOMINATOR_SCALAR / FEED_SCALAR;
```suggestion
            return answer * 1e18 / FEED_SCALAR;
```

2024-04-22 11:34 UTC, alcueca commented on src/chainlink/ChainlinkOracle.sol
> +            return NUMERATOR_SCALAR * FEED_SCALAR / answer;
```suggestion
            return 1e18 * FEED_SCALAR / answer;
```

2024-04-22 11:34 UTC, alcueca commented on src/chainlink/ChainlinkOracle.sol
> +    function _getAnswer(address base, address quote) internal view returns (uint256) {
I like natspec in internal functions as well.

2024-04-23 05:37 UTC, totomanov commented
> I wonder if it is too confusing and unexpected that prices are always FP18 regardless of the quote asset. Everyone seems to get it wrong.

I do find it sort of unintuitive. The interface currently mimics a DEX swap interface. `baseAmount` is in units of `base`, so why isn't the returned amount in units of `quote`?

Most applications that need oracles use them to arrive at a price-equivalent amount of something. In this case FP18 isn't helpful and the consumer will need to convert decimals after getting the value.

2024-04-29 09:54 UTC, alcueca commented
> why isn't the returned amount in units of quote?
Because you use `valueOf` for that.

> Most applications that need oracles use them to arrive at a price-equivalent amount of something. In this case FP18 isn't helpful and the consumer will need to convert decimals after getting the value.
True, but to get the "price-equivalent amount of something" you use `valueOf`.

`priceOf` doesn't return a price-equivalent amount of something, it returns a factor that ignores that the assets might have different decimals, like this:

![image](https://github.com/alcueca/oracles/assets/38806121/41304441-f04c-4e86-a024-5c80e8e2de90)
[link](https://www.coinbase.com/en-pt/converter/eth/usdc)

2024-04-29 09:56 UTC, alcueca approved these changes
LGTM, but let's discuss whether `priceOf` shoould return an FP18, or be like `valueOf(10**base.decimals())`.

2024-04-30 06:54 UTC, merged